title: Peter Palaga
description: A software engineer at Red Hat Integration, working mostly on Apache Camel Quarkus, coauthor of mvnd, srcdeps and ec4j.
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
date_format: '%b %-d, %Y'
github: https://github.com/ppalaga/ppalaga.github.io
related_posts_count: 5
url: https://peter.palaga.org
baseurl: ""

collections:
  category:
    output: true

# GitHub
username: ppalaga
repo: ppalaga.github.io
branch: main

# Jekyll source / destination
source:               .
destination:          _site

plugins:
  - jekyll-regex-replace
  - jekyll-feed
